### ISSUE TITLE
AttributesWithContext(ua.AttributeIDAccessLevel) always returns None, should be CurrentRead/CurrentWrite

### ISSUE THREAD

**Issue by JulianKrmr** [gopcua/opcua#635] opened 2023-02-02 11:12 UTC
Following the browse example provided in the examples folder, the value of AttributeIDAccessLevel is always 0, I tested it with a Simulation Server with the permission set to CurrentRead and CurrentWrite and I can use both write and read on the node. 
<img width="997" alt="Bildschirmfoto 2023-02-02 um 12 14 53" src="https://user-images.githubusercontent.com/92650905/216309997-477887da-71c5-4136-8346-129f01e0cd74.png">

**Comment by JulianKrmr** [comment] 2023-03-01 17:24
Can I get a reply to this please? :)

**Comment by magiconair** [comment] 2023-03-01 18:33
I'm currently on vacation but can have a look next week when I'm back. @kung-foo maybe you have some time before that?

**Comment by JulianKrmr** [comment] 2023-03-22 10:53
Push
I would be very thankful for help on this one!

**Comment by magiconair** [comment] 2023-03-22 19:32
I'll try to have a look tomorrow

**Comment by magiconair** [comment] 2023-03-23 09:20
Hmm, can't reproduce this...

<img width="884" alt="image" src="https://user-images.githubusercontent.com/229005/227157975-0101dad2-c7d2-49ac-9739-8e8fb67a149f.png">

<img width="838" alt="image" src="https://user-images.githubusercontent.com/229005/227158049-04998dce-59cf-4066-8c75-3dc6a17036f4.png">

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/229005/227158102-6b2a3742-7e20-49f1-b343-6252234658f6.png">

**Comment by magiconair** [comment] 2023-03-23 09:22
Wait. I'm testing the wrong method

**Comment by magiconair** [comment] 2023-03-23 09:24
Hmm, still works ...

```go
// Copyright 2018-2020 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

package main

import (
	"context"
	"flag"
	"log"

	"github.com/gopcua/opcua"
	"github.com/gopcua/opcua/debug"
	"github.com/gopcua/opcua/ua"
)

func main() {
	var (
		endpoint = flag.String("endpoint", "opc.tcp://localhost:4840", "OPC UA Endpoint URL")
		nodeID   = flag.String("node", "", "NodeID to read")
	)
	flag.BoolVar(&debug.Enable, "debug", false, "enable debug logging")
	flag.Parse()
	log.SetFlags(0)

	ctx := context.Background()

	c := opcua.NewClient(*endpoint, opcua.SecurityMode(ua.MessageSecurityModeNone))
	if err := c.Connect(ctx); err != nil {
		log.Fatal(err)
	}
	defer c.CloseWithContext(ctx)

	id, err := ua.ParseNodeID(*nodeID)
	if err != nil {
		log.Fatalf("invalid node id: %v", err)
	}

	req := &ua.ReadRequest{
		MaxAge: 2000,
		NodesToRead: []*ua.ReadValueID{
			{NodeID: id, AttributeID: ua.AttributeIDAccessLevel},
		},
		TimestampsToReturn: ua.TimestampsToReturnBoth,
	}

	resp, err := c.ReadWithContext(ctx, req)
	if err != nil {
		log.Fatalf("Read failed: %s", err)
	}
	if resp.Results[0].Status != ua.StatusOK {
		log.Fatalf("Status not OK: %v", resp.Results[0].Status)
	}
	log.Printf("%#v", resp.Results[0].Value.Value())

	resp2, err := c.Node(id).AttributesWithContext(ctx, ua.AttributeIDAccessLevel)
	if err != nil {
		log.Fatalf("AttributesWithContext failed: %s", err)
	}
	if resp2[0].Status != ua.StatusOK {
		log.Fatalf("Status not OK: %v", resp2[0].Status)
	}
	log.Printf("%#v", resp2[0].Value.Value())
}
```

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/229005/227159138-8774d8a6-f7b2-48f6-bf2e-0a1a4d01bfe2.png">

**Comment by JulianKrmr** [comment] 2023-03-23 09:27
Thanks alot for checking, I guess there must be a mistake by my side then. I will look it up on my side again and then will give an update here.

**Comment by magiconair** [comment] 2023-03-23 09:28
No worries. I'll close it. Please re-open if necessary.

**Closed as completed by magiconair** 2023-03-23 09:28 UTC
Labels: need feedback
